[meta]
title = "Huong's skillradar"
categories = [ "Platforms", "Frameworks", "Tools", "Techniques" ]
levels = [ "Novice", "Intermediate", "Advanced", "Veteran" ]

[[blips]]
category = 3
link = ""
description = "Fundamental Coding Skills: Algorithms and Data Structures"
title = "Programming"
level = 0

  [[blips.changes]]
  date = "2024-04-14"
  newLevel = 1
  text = "HackerRank Problem Solving (Basic) Certificate"

[[blips]]
category = 2
link = ""
description = "Jenkins"
title = "Jenkins"
level = 0

  [[blips.changes]]
  date = "2024-04-14"
  newLevel = 2
  text = "Main build tool since 2013"

[[blips]]
category = 1
link = ""
description = "Angular"
title = "Angular"
level = 0

  [[blips.changes]]
  date = "2024-04-14"
  newLevel = 1
  text = "Main frontend framework since 2022"

[[blips]]
category = 1
link = ""
description = "SpringBoot"
title = "SpringBoot"
level = 0

  [[blips.changes]]
  date = "2024-04-14"
  newLevel = 1
  text = "Main Java framework used for developing web applications since 2022"

[[blips]]
category = 0
link = ""
description = "OpenShift"
title = "OpenShift"
level = 0

  [[blips.changes]]
  date = "2024-04-14"
  newLevel = 2
  text = "Main container orchestration tool used since 2018"

[[blips]]
category = 0
link = ""
description = "PostgreSQL"
title = "PostgreSQL"
level = 0

  [[blips.changes]]
  date = "2024-04-14"
  newLevel = 2
  text = "Main relational database used since 2013"

[[blips]]
category = 0
link = ""
description = "Java"
title = "Java"
level = 0

  [[blips.changes]]
  date = "2024-04-14"
  newLevel = 2
  text = "Main programming language used since 2013"
